### ISSUE TITLE
Adding some 00 in front of time

### ISSUE THREAD

**Issue by lunadiotic** [zezo010/Elgindy-VTT-to-SRT-Subtitle-Converter#1]
Thank you for creating a very useful application.

I have a problem with the difference in the results of the conversion.
Where if I use an online converter, the result will add two 00 numbers at the beginning and can be read by the media player.
While the results of this application he did not add two 00 at the beginning.

This is from online converter
![Screenshot_1](https://user-images.githubusercontent.com/18319373/61993981-c6e92400-b09e-11e9-8277-3961dfb5eb56.png)

This from your app
![Screenshot_2](https://user-images.githubusercontent.com/18319373/61993982-d23c4f80-b09e-11e9-9302-5d729e8f070a.png)

**Comment by zezo010** [comment]
Already updated, I will upload it now

**Comment by eminarslan** [comment]
Any updates on this? @zezo010

**Comment by zezo010** [comment]
> 
> 
> Any updates on this? @zezo010

Solved

**Comment by zezo010** [comment]
> 
> 
> Thank you for creating a very useful application.
> 

Solved

**Comment by zezo010** [comment]
Fixed and closed
